### ISSUE TITLE
Simple confusing typo on doc

### ISSUE THREAD

**Issue by psorianom** [ANSSI-FR/SecuML#13]
Hello,

There is a small confusing typo in the documentation: in `getting_started.lingspam.rst`, in the *Annotating a Dataset with a Reduced Workload* section, the example command you show is :
`SecuML_ILAB SpamHam lingspam --secuml-conf <conf_file >Ilab --auto --budget 500`

I think it would be clearer if the right bracket of _conf\_file_ is not preceded by a space and not immediately followed by _Ilab_, like so:
`SecuML_ILAB SpamHam lingspam --secuml-conf <conf_file> Ilab --auto --budget 500`

Thanks,
Pavel

**Comment by ab-anssi** [comment]
Thanks for your feedback !
