### ISSUE TITLE
First experiment

### ISSUE THREAD

**Issue by botta633** [ANSSI-FR/SecuML#15]
Hello, 
Thank you for your amazing work. I finished installing SecuML, yet I don't know how to start experimenting with it. I am required to try some experiments for a research project but I don't know how to start. What should be my first step to do after installing it?
Thanks again, and sorry if my question is quite silly.

**Comment by ab-anssi** [comment]
Hello,

If you want you can start with analyzing the use case data stored in the repository (spam detection). See [Use Case: Spam Detection](https://anssi-fr.github.io/SecuML/getting_started.lingspam.html).

Then, if you want to analyze your own data, you first need to store them in the right format. See [Data](https://anssi-fr.github.io/SecuML/SecuML.Data.html) for more information.
Once you have stored your data in the right format, you can run various analyses : [training and evaluating a supervised ou unsupervised model](https://anssi-fr.github.io/SecuML/SecuML.DIADEM.html), [clustering](https://anssi-fr.github.io/SecuML/SecuML.clustering.html), [projection for data visualization](https://anssi-fr.github.io/SecuML/SecuML.projection.html), [features analysis](https://anssi-fr.github.io/SecuML/SecuML.stats.html), [rare category detection](https://anssi-fr.github.io/SecuML/SecuML.RCD.html), and [active learning to annotate a training dataset with a low workload](https://anssi-fr.github.io/SecuML/SecuML.ILAB.html).

You can refer to [https://anssi-fr.github.io/SecuML/index.html](https://anssi-fr.github.io/SecuML/index.html) for the whole documentation.

**Comment by botta633** [comment]
I thought I managed to install it but when I tried to launch the webserver it didn't find the command SecuML_Server. I don't get the line of "pip install <path to secumL project" which project do you mean?

**Comment by botta633** [comment]
There is no setup.py file in the directory of venv_SecuML

**Comment by ab-anssi** [comment]
`<path to secumL project>` is the path of the SecuML directory you have cloned from gitHub, which contains the install file `setup.py`.
