### ISSUE TITLE
"Getting started"

### ISSUE THREAD

**Issue by HoneyJack** [ANSSI-FR/SecuML#4]
Hi guys, I really like your project,
 could you prepare a "getting started" to quick testing? 
thank you so much!
 nice tool!

**Comment by ab-anssi** [comment]
Thanks for your interest.

A dataset is provided in the repo for quick testing (see `input_data/SpamHam/lingspam`).

The folder `doc` contains examples for classification, projection, active learning, etc … To run the examples with the dataset provided you should set `project` to `SpamHam`, and `dataset` to `lingspam`.

The examples are perhaps not sufficiently clear. I will try to improve them.

**Comment by ab-anssi** [comment]
I have just added a "Getting Started" section to the README.
Feel free to send us feedback to improve it if you encounter difficulties while following the instructions.

**Comment by HoneyJack** [comment]
I forked it to create a "Getting started" this weekend. Luckily You did first, thanks!
