### ISSUE TITLE
Delete experiments that have not completed successfully

### ISSUE THREAD

**Issue by ab-anssi** [ANSSI-FR/SecuML#7]
Currently the failed experiments are not deleted. So, they can be accessed from the SecuML web interface, but their display fails. 
They should be deleted to avoid these display errors.

**Comment by ab-anssi** [comment]
@djKooks, the name of the output directories correspond to the experiment ids that are managed automatically by the database (autoincrement id). Why do you like the change the way they are generated ?
Anyway, this question is not related to this issue. Can you open a new one if necessary please ?

**Comment by djKooks** [comment]
@ab-anssi oh, yeah you're right. It would be good to let in current status. Just ignore my suggestion.
